import {
  assumptionIdSchema,
  diagramIdSchema,
  elementIdSchema,
  mitigationIdSchema,
  threatIdSchema,
} from './ids.js';
import { modelSchema } from './model.js';

type CheckDef = {
  readonly check: string;
  readonly minimum?: number;
  readonly value?: number;
  readonly inclusive?: boolean;
};

type SchemaDef = {
  readonly type: string;
  readonly format?: string;
  readonly checks?: readonly { readonly _zod: { readonly def: CheckDef } }[];
  readonly shape?: Readonly<Record<string, Schema>>;
  readonly options?: readonly Schema[];
  readonly discriminator?: string;
  readonly entries?: Readonly<Record<string, string>>;
  readonly values?: readonly string[];
  readonly element?: Schema;
};

type Schema = { readonly def: SchemaDef };

const brands: readonly (readonly [Schema, string])[] = [
  [elementIdSchema, 'ElementId'],
  [diagramIdSchema, 'DiagramId'],
  [threatIdSchema, 'ThreatId'],
  [mitigationIdSchema, 'MitigationId'],
  [assumptionIdSchema, 'AssumptionId'],
];

const preamble = [
  'The whole internal model, expanded from the zod schemas that define it.',
  '`parseModel` is the only way a model value comes into existence, and it',
  'enforces more than the shapes below: element, diagram, threat, mitigation',
  'and assumption ids unique where they must be, threat numbers unique and',
  'never above `lastIssuedThreatNumber`, flow endpoints anchored inside their',
  'own diagram and never to the flow itself, and every element and threat',
  'reference resolving.',
  '',
  'Generated by `src/lib/schema-report.ts` and checked against the schemas on',
  'every test run, so it cannot fall behind them. Regenerate it with',
  '`pnpm nx test @panoptes/model -- -u`.',
];

/**
 * The internal model's whole shape as markdown, walked from the schemas
 * rather than written out, so the document and the schemas cannot disagree.
 * Every field is expanded where it stands rather than referred to a section
 * of its own, which makes the document long and leaves nothing to chase.
 */
export function renderModelSchema(): string {
  return [
    '# Internal model schema',
    '',
    ...preamble,
    '',
    renderSchema(modelSchema),
    '',
  ].join('\n');
}

/**
 * One schema's fields as markdown, the body {@link renderModelSchema} is
 * built from. A constraint it has no words for is left undescribed rather
 * than described wrongly, so a bound the model gains later reads as the
 * plain type until this learns to word it.
 */
export function renderSchema(schema: Schema): string {
  return expand(schema, '').join('\n');
}

function expand(schema: Schema, indent: string): string[] {
  const def = schema.def;
  if (def.shape) {
    return Object.entries(def.shape).flatMap(([name, field]) =>
      fieldLines(name, field, indent),
    );
  }
  if (def.element) {
    return expand(def.element, indent);
  }
  const discriminator = def.discriminator;
  if (def.options && discriminator !== undefined) {
    return def.options.flatMap((option) =>
      variant(option, discriminator, indent),
    );
  }
  return [];
}

function fieldLines(name: string, schema: Schema, indent: string): string[] {
  return [
    `${indent}- \`${name}\`: ${summary(schema)}`,
    ...expand(schema, `${indent}  `),
  ];
}

function variant(
  option: Schema,
  discriminator: string,
  indent: string,
): string[] {
  const shape = { ...option.def.shape };
  return [
    `${indent}- when \`${discriminator}\` is ${summary(shape[discriminator])}`,
    ...Object.entries(shape)
      .filter(([name]) => name !== discriminator)
      .flatMap(([name, field]) => fieldLines(name, field, `${indent}  `)),
  ];
}

function summary(schema: Schema): string {
  const def = schema.def;
  const brand = brands.find(([branded]) => branded === schema);
  if (brand) {
    return `${brand[1]} (${scalar(def)})`;
  }
  if (def.shape) {
    return 'object';
  }
  if (def.element) {
    return `list of ${listed(def)}${summary(def.element)}`;
  }
  if (def.options) {
    return `one of ${String(def.options.length)}, told apart by \`${String(def.discriminator)}\``;
  }
  if (def.entries) {
    return `one of ${Object.values(def.entries)
      .map((value) => `\`${value}\``)
      .join(', ')}`;
  }
  if (def.values) {
    return `\`${def.values.join('')}\``;
  }
  return scalar(def);
}

function listed(def: SchemaDef): string {
  const least = (def.checks ?? []).find(
    (check) => check._zod.def.minimum !== undefined,
  )?._zod.def.minimum;
  return least === undefined ? '' : `at least ${String(least)} `;
}

function scalar(def: SchemaDef): string {
  const kind = def.format === 'safeint' ? 'integer' : def.type;
  const bounds = (def.checks ?? []).flatMap((check) => bound(check._zod.def));
  return [kind, ...bounds].join(', ');
}

function bound(check: CheckDef): string[] {
  if (check.minimum !== undefined) {
    return [`at least ${String(check.minimum)} character`];
  }
  if (check.value !== undefined) {
    return [
      check.inclusive === true
        ? `${String(check.value)} or more`
        : `greater than ${String(check.value)}`,
    ];
  }
  return [];
}
